# Generated by Django 2.2.8 on 2020-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtithiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
